### ISSUE TITLE
Initial Project Plan needed

### ISSUE THREAD

**Issue by EHWUSF** [EHWUSF/HS68_2018_Project_1#1]
We can revise the plan as we go, but we need to start with at least an overview.

**Comment by rohitchadaram** [comment]
Would you like us to make the group ourselves and work on the project as a group ?

**Comment by EHWUSF** [comment]
I think the group decision has been made to simply rely on the individual Issue discussions rather than put together an overall planning document, so I'll go ahead and close this.

Just to note here before closing this Issue; as discussed in class and the assignment document, it is a class-wide group collaboration, although everyone will be graded primarily on their individual contributions.
