### ISSUE TITLE
Data Visualization- Keys and Labels 

### ISSUE THREAD

**Issue by NikitaThomas** [EHWUSF/HS68_2018_Project_1#9]
I believe it would be helpful to have a file within the Data Visualization module that makes the labeling of axis and keys more efficient. I propose having the file prompt the user what they want as axis titles, key labels, and colors for the linear regression plot making visualization easier and quicker to output.

**Comment by rohitchadaram** [comment]
I like the idea but how would you generalize to all the plots available for linear regression, I'm sure there are plenty of plots that can be done, infact you can do 3D,4D... plots so what's your plan to make it work for all of them? Or do you just plan to make it for a sample 2D plot ?

**Comment by NikitaThomas** [comment]
I was originally thinking just for 2D but we can also expand it further by first prompting the user what type of plot they want to output and then taking that input to produce the plot with the appropriate labels. I will have to do more research on what all plots we want to include however we can start by referencing all the available plots for linear regression in matplotlib and go from there.

**Comment by kamehta2** [comment]
This is a good idea. You can also add prompt for ascending/ descending, for plots like bar chart, histogram etc.
